name: CS671 Deep Learning
markdown: redcarpet
pygments: true
gituser: shreyasbapat/CS671-Deep-Learning-2019
paginate: 5
paginate_path: "page:num"
email: shreyasbapat
#disqus: bitwiser
ga_id: UA-47902363-1
ga_domain: shreyasb.com
desc: Website for Group 1 CS671 IIT Mandi
keywords: CS671, IITMandi, Deep, Learning
twitter: astroshreyas
